### ISSUE TITLE
DAI: 提供 persistent binding 功能

### ISSUE THREAD

**Issue by gary1209** [IoTtalk/iottalk-py#12]
@iblis17

**Comment by iblislin** [comment]
@Ksoy 
1. 以 `register` function 的 keyword argument 提供這個功能，不過 naming 要確認。
2. MQTT last will message 在 static binding 的 case 上面有沒有不同？

**Comment by iblislin** [comment]
最後討論出來參數用 `persistent_binding` 命名。

**Comment by iblislin** [comment]
後來發現是 DAI 控制著 register/deregister

**Comment by iblislin** [comment]
@Ksoy 這個 JS 的 DAN 有沒有實作啊？

**Comment by Ksoy** [comment]
應該沒有，我去開個issue吧

**Comment by Ksoy** [comment]
等等，不過 JS 沒有 DAI 啊，這個功能是做在 DAI 上的

**Comment by iblislin** [comment]
那麼 要生出個 DAI 嗎？

**Comment by Ksoy** [comment]
看來是要， https://github.com/IoTtalk/iottalk-js/issues/24
