### ISSUE TITLE
註冊網址錯誤無法給予正確的提示

### ISSUE THREAD

**Issue by Ksoy** [IoTtalk/iottalk-py#16]
https://github.com/IoTtalk/iottalk-py/blob/1509a7adbdad83ce2b9561683abf0f7fdd1d386a/iottalkpy/dan.py#L388

當並非系統回復的訊息時，會導致無法解析 response 的 json，
進而引發 decode error。

**Comment by iblislin** [comment]
改成遇到 decode error 耶轉成 RegistractionError 丟出去？

**Comment by iblislin** [comment]
啊 我知道了

**Comment by iblislin** [comment]
我改嗎？還是找誰改？

**Comment by Ksoy** [comment]
你有空就改一下吧，我要去開會了

**Comment by iblislin** [comment]
好
