### ISSUE TITLE
provide a programmatic API to operate DAI

### ISSUE THREAD

**Issue by Ksoy** [IoTtalk/iottalk-py#21]
1. rebuild dai to class DAI for multi-use  
2. rename dai.main -> DAI.start  
3. support nonblocking on main(start)
  use new argument `block=true`

**Comment by iblislin** [comment]
考慮多重 DAI

**Comment by Ksoy** [comment]
關於那個 `app.__dict__.get(xxx)`，   
因為改用load_module了，要不要改成用 `getattr(app, xxx)`去取

**Comment by iblislin** [comment]
`__dict__` 跟 `getattr` 的 output 會因為 load_module 而改變嗎？

**Comment by Ksoy** [comment]
我不知道誒，只是覺得 `__dict__`很醜

**Comment by Ksoy** [comment]
然後其實我想提供一個function是可以直接塞參數的，不是像這種被動讀module的

**Comment by iblislin** [comment]
> 然後其實我想提供一個function是可以直接塞參數的，不是像這種被動讀module的

具體是？

**Comment by iblislin** [comment]
> 我不知道誒，只是覺得 `__dict__` 很醜

output 沒變就沒差，想改就改

**Comment by Ksoy** [comment]
> > 然後其實我想提供一個function是可以直接塞參數的，不是像這種被動讀module的
> 
> 具體是？

現在是 main(app)
main 做了二件事，extract app 的資料，跟實際執行 DAI

如果延用這樣的話對多重 DAI 來說很難用，變成每個 DA 都要先包成 module 再塞進去
我比較想拆成 load_modele(app) 只做 extract，
多一個 DAI(api_url, device_name, device_model, ...) 做執行 DAI

多重使用者在用的時候就可以直接
dai = DAI(...)
dai.start()

**Comment by iblislin** [comment]
好，繼承 `threading.Thread` 或是 Process 吧？
